# Generated by Django 6.1 on 2026-08-12 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDE', 'Validé')], default='EN_COURS', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.IntegerField()),
                ('quantite_physique', models.IntegerField(blank=True, null=True)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.inventaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit')),
            ],
        ),
    ]
