# Generated by Django 6.1 on 2026-08-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_initial'),
        ('accounts', '0006_add_inventaire_permissions'),
    ]

    operations = [
    ]
